spring.application.name=autowashpro

# ==========================================
# Configure Database SQLServer
# ==========================================
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true;databaseName=AutoWashPro
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2014Dialect
spring.jpa.hibernate.ddl-auto =update


# ==========================================
# Configure Gmail to send OTPs
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=autowahpro@gmail.com
spring.mail.password=yvhkvfcntpedouve
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true